myapp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

contact/models.py
from django.db import models

class Contact(models.Model):  
    firstname = models.CharField(max_length=100)  
    lastname = models.CharField(max_length=100)  
    email = models.CharField(max_length=100)  
    mobile = models.IntegerField()  
    age = models.IntegerField()  
    
    def __str__(self):
        return self.firstname
    class Meta:  
        db_table = "contact"

contact/forms.py
from django import forms  
from contact.models import Contact  
class ContactForm(forms.ModelForm):  
    class Meta:  
        model = Contact  
        fields = "__all__"  

contact/views.py
from django.shortcuts import render, redirect  
from contact.forms import ContactForm  
from contact.models import Contact 


def create(request):  
    if request.method == "POST":  
        form = ContactForm(request.POST)  
        # if form.is_valid():  
        try:  
            form.save()  
            return redirect('/show')  
        except:  
            pass  
    else:  
        form = ContactForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    contacts = Contact.objects.all()  
    return render(request,"show.html",{'contacts':contacts})  
def edit(request, id):  
    contact = Contact.objects.get(id=id)  
    return render(request,'edit.html', {'contact':contact})  
def update(request, id):  
    contact = Contact.objects.get(id=id)  
    form = ContactForm(request.POST, instance = contact)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'contact': contact})  
def destroy(request, id):  
    contact = Contact.objects.get(id=id)  
    contact.delete()  
    return redirect("/show")  

contact/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}" /> -->
  </head>
  <body>
    <div class="container">
      <div class="row">
        <form method="POST" class="post-form" action="/update/{{contact.id}}">
          {% csrf_token %}
          <div class="container">
            <br />
            <div class="form-group row">
              <label class="col-sm-1 col-form-label"></label>
              <div class="col-sm-4">
                <h3>Update Details</h3>
              </div>
            </div>
            <!-- <div class="form-group row">
              <label class="col-sm-2 col-form-label">Id:</label>
              <div class="col-sm-4">
                <input
                  type="text"
                  name="id"
                  id="id_id"
                  required
                  maxlength="20"
                  value="{{ contact.id }}"
                />
              </div>
            </div> -->
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">First Name:</label>
              <div class="col-sm-4">
                <input
                  type="text"
                  name="firstname"
                  id="id_firstname"
                  required
                  maxlength="100"
                  value="{{ contact.firstname }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Last Name:</label>
              <div class="col-sm-4">
                <input
                  type="text"
                  name="lastname"
                  id="id_lastname"
                  required
                  maxlength="100"
                  value="{{ contact.lastname }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Email:</label>
              <div class="col-sm-4">
                <input
                  type="email"
                  name="email"
                  id="id_email"
                  required
                  maxlength="254"
                  value="{{ contact.email }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Mobile:</label>
              <div class="col-sm-4">
                <input
                  type="number"
                  name="mobile"
                  id="id_mobile"
                  required
                  maxlength="254"
                  value="{{ contact.mobile }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Age:</label>
              <div class="col-sm-4">
                <input
                  type="number"
                  name="age"
                  id="id_age"
                  required
                  maxlength="15"
                  value="{{ contact.age }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-1 col-form-label"></label>
              <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Update</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

contact/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}" /> -->
  </head>
  <body>
    <div class="container">
      <div class="row">
        <form method="POST" class="post-form" action="/create">
          {% csrf_token %}
          <div class="container">
            <br />
            <div class="form-group row">
              <label class="col-sm-1 col-form-label"></label>
              <div class="col-sm-4">
                <h3>Contact Details</h3>
              </div>
            </div>
            <!-- <div class="form-group row">
                <label class="col-sm-2 col-form-label">Id:</label>
                <div class="col-sm-4">{{ form.id }}</div>
              </div> -->
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">First Name:</label>
              <div class="col-sm-4">{{ form.firstname }}</div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Last Name:</label>
              <div class="col-sm-4">{{ form.lastname }}</div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Email:</label>
              <div class="col-sm-4">{{ form.email }}</div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Mobile:</label>
              <div class="col-sm-4">{{ form.mobile }}</div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Age:</label>
              <div class="col-sm-4">{{ form.age }}</div>
            </div>

            <div class="form-group row">
              <label class="col-sm-1 col-form-label"></label>
              <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

contact/templates/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Contact Records</title>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}" /> -->
  </head>
  <body>
    <div class="container">
      <div class="row">
        <table class="table table-striped table-bordered table-sm">
          <thead class="thead-dark">
            <tr>
              <!-- <th>ID</th> -->
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Mobile</th>
              <th>Age</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for contact in contacts %}
            <tr>
              <!-- <td>{{ contact.id }}</td> -->
              <td>{{ contact.firstname }}</td>
              <td>{{ contact.lastname }}</td>
              <td>{{ contact.email }}</td>
              <td>{{ contact.mobile }}</td>
              <td>{{ contact.age }}</td>
              <td>
                <a href="/delete/{{ contact.id }}" class="btn btn-danger"
                  >Delete</a
                >
                <a href="/edit/{{ contact.id }}" class="btn btn-primary"
                  >Edit</a
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <br />
        <a href="/create" class="btn btn-primary">Add New Record</a>
        <a href="/create" class="btn btn-primary">Add New Record</a>

      </div>
    </div>
  </body>
</html>